/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Versions of this package and its first-party dependencies */
        get: operations["version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a token for a grant flow.
         *     Implements https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.3 */
        post: operations["token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upsert Model */
        post: operations["model_upsert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/model/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model by id */
        get: operations["model_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get PersonModels */
        get: operations["models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v0/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get profile */
        get: operations["profile_get"];
        put?: never;
        /** Upsert Profile */
        post: operations["profile_upsert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/secured/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout a user (uses provided Bearer token from Header) */
        post: operations["logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/secured/secret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Shows secret to authenticated user (uses provided Bearer token from Header) */
        get: operations["secret_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/crawl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST url to crawl */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description URL to crawl */
            requestBody?: {
                content: {
                    /** @example {
                     *       "url": "https://example.com"
                     *     } */
                    "application/json": components["schemas"]["ScraperPostBody"];
                };
            };
            responses: {
                /** @description Crawled process update */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ScraperPostBodyResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/crawl/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET crawled result */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of crawled result */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Crawled result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CrawledResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/swap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST to faceswap */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Body to faceswap */
            requestBody?: {
                content: {
                    /** @example {
                     *       "model_img_url": "https://a.com/a.jpg",
                     *       "user_img_url": "data:image/jpg;base64,fa"
                     *     } */
                    "application/json": components["schemas"]["SwapPostRequest"];
                };
            };
            responses: {
                /** @description Faceswap response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SwapPostResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CrawledResult: {
            /** Format: int64 */
            completed: number;
            /** Format: int64 */
            creditsUsed: number;
            data: unknown[];
            expiresAt: string;
            status: string;
            success: boolean;
            /** Format: int64 */
            total: number;
        };
        /** @description Create Struct for a row in table `person_models` for [`PersonModels`] */
        CreatePersonModels: {
            /**
             * Format: int32
             * @description Field representing column `bust_mm`
             */
            bust_mm?: number | null;
            /** @description Field representing column `hair_colour` */
            hair_colour?: string | null;
            /**
             * Format: int32
             * @description Field representing column `height_mm`
             */
            height_mm?: number | null;
            /**
             * Format: int32
             * @description Field representing column `hip_mm`
             */
            hip_mm?: number | null;
            /** @description Field representing column `male` */
            male?: boolean | null;
            /** @description Field representing column `skin_colour` */
            skin_colour?: string | null;
            /** @description Field representing column `skin_undertone` */
            skin_undertone?: string | null;
            /** @description Field representing column `url` */
            url?: string | null;
            /**
             * Format: int32
             * @description Field representing column `waist_mm`
             */
            waist_mm?: number | null;
            /**
             * Format: int32
             * @description Field representing column `weight_g`
             */
            weight_g?: number | null;
        };
        /** @description Create Struct for a row in table `profiles` for [`Profiles`] */
        CreateProfiles: {
            /** @description Field representing column `alias` */
            alias: string;
            /**
             * Format: int32
             * @description Field representing column `bust_mm`
             */
            bust_mm?: number | null;
            /** @description Field representing column `hair_colour` */
            hair_colour?: string | null;
            /**
             * Format: int32
             * @description Field representing column `height_mm`
             */
            height_mm?: number | null;
            /**
             * Format: int32
             * @description Field representing column `hip_mm`
             */
            hip_mm?: number | null;
            /** @description Field representing column `male` */
            male?: boolean | null;
            /** @description Field representing column `profile_image_url` */
            profile_image_url?: string | null;
            /** @description Field representing column `skin_colour` */
            skin_colour?: string | null;
            /** @description Field representing column `skin_undertone` */
            skin_undertone?: string | null;
            /** @description Field representing column `username` */
            username: string;
            /**
             * Format: int32
             * @description Field representing column `waist_mm`
             */
            waist_mm?: number | null;
            /**
             * Format: int32
             * @description Field representing column `weight_g`
             */
            weight_g?: number | null;
        };
        /** @enum {string} */
        GrantType: "password" | "authorization_code" | "client_credentials" | "refresh_token";
        ScraperPostBody: {
            url: string;
        };
        ScraperPostBodyResponse: {
            id: string;
            success: boolean;
            url: string;
        };
        SwapPostRequest: {
            model_img_url: string;
            user_img_url: string;
        };
        SwapPostResponse: {
            output_url: string;
            status: string;
        };
        TokenRequest: {
            /**
             * @description optional client ID (required, for example, in RFC6749's non password non refresh grant flow)
             * @example null
             */
            client_id?: string | null;
            /**
             * @description optional client secret (as used, e.g., in RFC6749's non (password|refresh) grant flow)
             * @example null
             */
            client_secret?: string | null;
            /**
             * @description optional code (required, e.g., in datatracker.ietf.org/doc/html/rfc6749#section-4.1.3)
             * @example null
             */
            code?: string | null;
            /** @description RFC6749 grant type */
            grant_type: components["schemas"]["GrantType"];
            /**
             * @description optional password (as used, for example, in RFC6749's password grant flow)
             * @example pass0
             */
            password?: string | null;
            /**
             * @description optional redirect_uri (used, e.g., in datatracker.ietf.org/doc/html/rfc6749#section-4.1.3)
             * @example null
             */
            redirect_uri?: string | null;
            /**
             * @description optional refresh token (as used, for example, in RFC6749's refresh grant flow)
             * @example null
             */
            refresh_token?: string | null;
            /**
             * @description optional username (as used, for example, in RFC6749's password grant flow)
             * @example user0
             */
            username?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description Token created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized User */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found User */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    model_upsert_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePersonModels"];
            };
        };
        responses: {
            /** @description Model created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    model_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Model id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Model found from database */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PersonModels found in database */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile for user associated with access token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found: User does not have associated profile */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    profile_upsert_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProfiles"];
            };
        };
        responses: {
            /** @description Profile created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorised: You tried to create a profile for another user */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    secret_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description secret endpoint */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
